version: '3.8'

services:
  product-service:
    image: "bepacked/product-service:latest"
    build:
      context: .
    container_name: product-service
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_ALIAS=db
    ports:
      - "8080:8080"
  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productdb
    ports:
      - "5432:5432"
    volumes:
      - ./log-directory:/var/lib/postgresql/data